<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.bitdreamit</groupId>
        <artifactId>serial-connector</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>serial-connector-distribution</artifactId>
    <packaging>pom</packaging>
    <dependencies>
        <dependency><groupId>com.bitdreamit</groupId><artifactId>serial-connector-shared</artifactId><version>${project.version}</version><type>jar</type></dependency>
        <dependency><groupId>com.bitdreamit</groupId><artifactId>serial-connector-server</artifactId><version>${project.version}</version><type>jar</type></dependency>
        <dependency><groupId>com.bitdreamit</groupId><artifactId>serial-connector-client</artifactId><version>${project.version}</version><type>jar</type></dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>com.kaurpalang</groupId><artifactId>mirth-plugin-maven-plugin</artifactId>
                <version>${mirth-plugin-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <goals><goal>generate-plugin-xml</goal><goal>package-plugin</goal></goals>
                    </execution>
                </executions>
                <configuration><pluginPath>${project.basedir}</pluginPath></configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId><artifactId>maven-jarsigner-plugin</artifactId>
                <version>${maven-jarsigner-plugin.version}</version>
                <executions>
                    <execution><id>sign</id><goals><goal>sign</goal></goals></execution>
                </executions>
                <configuration>
                    <keystore>${project.parent.basedir}/certificate/keystore.jks</keystore>
                    <alias>selfsigned</alias><storepass>storepass</storepass><keypass>keypass</keypass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>